### ISSUE TITLE
Plugin started hanging since version 1.2.0

### ISSUE THREAD

**Issue by chovyy** [cleydyr/dart-sass-maven-plugin#35] opened 2024-02-06 09:19 UTC
After a while after using version 1.2.0 of the plugin, I was no longer able to build my project since the plugin stucks after "Auto-detected operating system architecture: x64". The only way to build my project was to go back to version 1.1.0. 
I experienced this problem in different projects on a Linux machine and on Windows. Running the build with `-X` gives no further output.

**Comment by cleydyr** [comment] 2024-02-06 09:21
Can you reproduce the issue consistently? If so, can you take a thread dump of the process when it's hung and share it with us?

**Comment by chovyy** [comment] 2024-02-06 09:44
It was quite consistent, but after doing some successfull builds with 1.1.0, it now works again with 1.2.0. But when the problem arises again, I will do a thread dump.

**Comment by cleydyr** [comment] 2024-02-06 09:56
Cool. Let me know if you need any assistance meanwhile.

**Comment by lambdaupb** [comment] 2024-02-15 16:19
This is caused by a `403` response from the github api checking for the latest version of the dart sass artifact.
Github has fairly strict API request limits.
The error handling logic hangs for some reason.

I would recommend not relying on the api at all, as leads to flaky builds in CI jobs and gets the IP range blocked quickly.

A workaround is to set the compiler version explicitly in the configuration section.

For example: `<version>1.70.0</version>`

**Comment by cleydyr** [comment] 2024-02-15 17:15
Good catch, @lambdaupb! I've been able to reproduce it by exhausting my limit rate and executing the plugin.

Here's the stack trace obtained of the main thread when the plugin hangs:

```
"main" #1 prio=5 os_prio=31 cpu=1415,03ms elapsed=73,19s tid=0x000000015500c000 nid=0x2303 waiting on condition  [0x000000016fd81000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(java.base@17.0.2/Native Method)
	at org.kohsuke.github.RateLimitHandler$1.onError(RateLimitHandler.java:75)
	at org.kohsuke.github.RateLimitHandler.onError(RateLimitHandler.java:44)
	at org.kohsuke.github.GitHubClient.detectKnownErrors(GitHubClient.java:466)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:435)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:403)
	at org.kohsuke.github.Requester.fetch(Requester.java:85)
	at org.kohsuke.github.GHRepository.read(GHRepository.java:145)
	at org.kohsuke.github.GitHub.getRepository(GitHub.java:684)
	at com.github.cleydyr.dart.net.NetworkingGithubLatestVersionProvider.get(NetworkingGithubLatestVersionProvider.java:41)
	at com.github.cleydyr.maven.plugin.CompileSassMojo.verifyDefaultParameters(CompileSassMojo.java:338)
	at com.github.cleydyr.maven.plugin.CompileSassMojo.execute(CompileSassMojo.java:288)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.2/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.2/NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.2/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@17.0.2/Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)	
```

**Comment by cleydyr** [comment] 2024-02-15 19:54
The [default implementation](https://github.com/hub4j/github-api/blob/main/src/main/java/org/kohsuke/github/RateLimitHandler.java#L67-L69) of the error handler is to put the thread to sleep while waiting for the rate limit to be reset. I'll use another RateLimitHandler that doesn't wait but fails immediately.

@chovyy, as @lambdaupb recommended, you can pin the library version to avoid calling the GitHub REST API and hanging your build process.

**Comment by lambdaupb** [comment] 2024-02-15 20:08
A different error handler will at least let the user know what is happening, but builds will still randomly fail.

Maybe encourage users to set a fixed version, using "latest" will lead to non-repeatable builds in projects anyway.

Or maybe use the pub.dev page to check for the latest version instead.
https://pub.dev/packages/sass/versions

**Comment by chovyy** [comment] 2024-02-16 08:28
Great thanks for your effort. Good to know the reason now, and how to avoid it. 👍

**Comment by cleydyr** [comment] 2024-02-24 12:59
Included in v1.3.0. Closing this issue.

**Comment by melloware** [comment] 2024-02-24 13:10
I just tried 1.3.0 and getting this error.

```
[ERROR] Failed to execute goal io.github.cleydyr:dart-sass-maven-plugin:1.3.0:compile-sass (generate-css-using-sass) on project designer: Execution generate-css-using-sass of goal io.github.cleydyr:dart-sass-maven-plugin:1.3.0:compile-sass failed: 
A required class was missing while executing io.github.cleydyr:dart-sass-maven-plugin:1.3.0:compile-sass: org/apache/commons/io/build/AbstractStreamBuilder
```

My Maven and JDK info.

```
Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)
Maven home: C:\tools\apache-maven-3.9.5
Java version: 17.0.6, vendor: Eclipse Adoptium, runtime: C:\tools\jdk-17.0.6+10
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

```

**Comment by cleydyr** [comment] 2024-02-24 13:18
Weird. I can't reproduce it when using the plugin on another project.

```
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
```

```
openjdk 17.0.2 2022-01-18 LTS
OpenJDK Runtime Environment Zulu17.32+13-CA (build 17.0.2+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.32+13-CA (build 17.0.2+8-LTS, mixed mode, sharing)
```

 Does it generate a stack trace?

**Comment by melloware** [comment] 2024-02-24 13:25
yeah i think its because your plugin has Commons IO 2.11 and my Project has 2.15.1 so something is not lining up wiht Commons IO.

**Comment by cleydyr** [comment] 2024-02-24 13:26
Hey, @melloware. Can you share the project with me so I can test it myself?

**Comment by melloware** [comment] 2024-02-24 13:30
Sure here you go:
[theme-builder.zip](https://github.com/cleydyr/dart-sass-maven-plugin/files/14392999/theme-builder.zip)

If you run `mvn clean package` then you will see the error and then back it up to 1.2.0 it is working?

**Comment by cleydyr** [comment] 2024-02-24 13:34
No luck. It still works on my machine. I'll close this issue again. Let's continue on #37.

**Closed as completed by cleydyr** 2024-02-24 13:34 UTC
Labels: bug
