### ISSUE TITLE
Use fallback when current version is unavailable

### ISSUE THREAD

**Issue by BalusC** [cleydyr/dart-sass-maven-plugin#31] opened 2023-10-06 10:26 UTC
It's otherwise blocking builds, see also https://github.com/sass/dart-sass/issues/2110

The plugin should fallback to previous version when current version fails to download. If that also fails then fallback further to last successfully used locally cached version.

**Comment by cleydyr** [comment] 2023-10-06 13:46
Good catch, @BalusC. I'll address this. Thank you.

**Comment by melloware** [comment] 2023-10-06 13:57
you rock @cleydyr !

**Comment by cleydyr** [comment] 2023-10-07 16:56
The proposed implementation to make this plugin more resilient is to iterate through each release and each release artifact and check if an artifact name matches what's expected (`dart-sass-[VERSION]-[OS]-[ARCH].[EXTENSION]`). If there's a matching artifact, we'll use its release as the autodetected version.

Note: the results returned by [the GitHub API](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#list-releases) _seem to be_ sorted by the date of the tag/commit [[1](https://github.com/orgs/community/discussions/8226#discussioncomment-1728546)], though it's not documented on the API doc itself.

The plugin should not fall back to the locally cached version, as the Dart Sass autodetection is intended to be used in environments with an Internet connection [[2](https://github.com/cleydyr/dart-sass-maven-plugin#offline-operation)], which means it's also able to download at least one version with a matching artifact for all supported os-arch combinations (1.68.0 is one such version). Also, if there was a locally cached release to begin with, it would already be used, and the release download wouldn't be attempted.

**Comment by cleydyr** [comment] 2023-10-07 17:59
Issue fixed on version 1.2.0, already deployed and soon to be published on Maven Central.

**Comment by melloware** [comment] 2023-10-07 18:38
Confirmed its in Maven Central.

**Comment by cleydyr** [comment] 2023-10-07 18:51
Closing this now.

**Closed as completed by cleydyr** 2023-10-07 18:51 UTC
Labels: enhancement

**Comment by BalusC** [comment] 2023-10-08 12:08
fab
